### ISSUE TITLE
Exception executing REFER

### ISSUE THREAD

**Issue by fanavarro** [davidebolo1993/TRiCoLOR#17]
Hi, I am trying to profile a tandem repeat from a bam file. `TRiCoLOR SENSoR` is working fine, and it returns a valid BED:

```
#CHROM  START   END     COVMEAN COVSTD  COVCOLLAPSED
chr4    39347191        39347896        19.25   10.75   30,8.5
chr4    39350899        39351601        10.75   1.25    12,9.5
```
But, when I try to execute `TRiCoLOR REFER`, I get the following exception:
```

	 ______ ______  __  ______  ______  __      ______  ______    
	/\__  _/\  == \/\ \/\  ___\/\  __ \/\ \    /\  __ \/\  == \   
	\/_/\ \\ \  __<\ \ \ \ \___\ \ \/\ \ \ \___\ \ \/\ \ \  __<   
	   \ \_\\ \_\ \_\ \_\ \_____\ \_____\ \_____\ \_____\ \_\ \_\ 
	    \/_/ \/_/ /_/\/_/\/_____/\/_____/\/_____/\/_____/\/_/ /_/ v1.1

	
[22/02/2023 19:24:43][Message] TRiCoLOR REFER v1.1
[22/02/2023 19:24:43][Message] Using RegEx (.+?)\1{4,}
[22/02/2023 19:24:43][Message] Processing chromosome chr4
[22/02/2023 19:24:44][Message] Loading .mmi index for current chromosome
[22/02/2023 19:24:45][Message] Calling repetitions
[22/02/2023 19:24:45][Message] Writing reference repetitions to BED
[22/02/2023 19:24:45][Message] Writing haplotype1 repetitions to BED
[22/02/2023 19:24:45][Message] Writing haplotype2 repetitions to BED
[22/02/2023 19:24:45][Message] Writing haplotype1 consensus BAM
[22/02/2023 19:24:45][Message] Writing haplotype2 consensus BAM
Traceback (most recent call last):
  File "/home/user/mambaforge/envs/tricolor/bin/TRiCoLOR", line 33, in <module>
    sys.exit(load_entry_point('TRiCoLOR==1.1.0', 'console_scripts', 'TRiCoLOR')())
  File "/home/user/mambaforge/envs/tricolor/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/TRiCoLOR.py", line 194, in main
    args.func(parser, args)
  File "/home/user/mambaforge/envs/tricolor/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/TRiCoLOR.py", line 280, in run_subtool
    submodule.run(parser,args)
  File "/home/user/mambaforge/envs/tricolor/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/REFER.py", line 767, in run
    BamW(bamh,H2bam,os.path.abspath(c.OUT + '/haplotype2/TRiCoLOR.bam'))
  File "/home/user/mambaforge/envs/tricolor/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/REFER.py", line 224, in BamW
    s.reference_name=segments['RNAME']
  File "pysam/libcalignedsegment.pyx", line 1226, in pysam.libcalignedsegment.AlignedSegment.reference_name.__set__
ValueError: reference 4 does not exist in header
```
I have been inspecting my files, but I have no clue about what is happening, as all of them have 'chr4' and not only '4'. Could this be caused by different pysam version than the expected? I am creating a conda environment by using the following file:

```
name: tricolor
channels:
 - bioconda
 - conda-forge
dependencies:
 - python=3.8
 - bedtools
 - htslib
 - samtools
 - bcftools
 - minimap2
 - picard
 - java-jdk
 - longshot 
 - whatshap
```
Then, I'm executing `./configure` in the repo folder (I had to modify a file, see #16 ), and then `python setup.py install`.

**Comment by adarsh-pp** [comment]
Hi
I am also getting a error while runningg REFER. SENSoR ran normally and generated BED file. I used the same BED file for next step. But I am getting following error:

> 	 ______ ______  __  ______  ______  __      ______  ______    
> 	/\__  _/\  == \/\ \/\  ___\/\  __ \/\ \    /\  __ \/\  == \   
> 	\/_/\ \\ \  __<\ \ \ \ \___\ \ \/\ \ \ \___\ \ \/\ \ \  __<   
> 	   \ \_\\ \_\ \_\ \_\ \_____\ \_____\ \_____\ \_____\ \_\ \_\ 
> 	    \/_/ \/_/ /_/\/_/\/_____/\/_____/\/_____/\/_____/\/_/ /_/ v1.1	
> [17/04/2024 13:37:50][Message] TRiCoLOR REFER v1.1
> [17/04/2024 13:37:50][Message] Using RegEx (.+?)\1{4,}
> [17/04/2024 13:37:50][Message] Processing chromosome chr1
> [17/04/2024 13:37:50][Message] Creating .mmi index for current chromosome
> [17/04/2024 13:37:55][Message] Calling repetitions
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:779885-780586: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:1831550-1832251: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:8235922-8236755: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:10005192-10005893: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:15092083-15092784: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:18599169-18599870: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:22017839-22018540: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:23007739-23008440: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:23138657-23139358: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:28678543-28679246: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:55][Error] Unexpected error while processing region chr1:28808490-28809191: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:56][Error] Unexpected error while processing region chr1:35302935-35303753: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:56][Error] Unexpected error while processing region chr1:35304093-35305772: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:56][Error] Unexpected error while processing region chr1:35309543-35310262: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:56][Error] Unexpected error while processing region chr1:35847418-35848119: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:56][Error] Unexpected error while processing region chr1:37548384-37549085: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:56][Error] Unexpected error while processing region chr1:47533311-47534012: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:56][Error] Unexpected error while processing region chr1:54326865-54327572: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:56][Error] Unexpected error while processing region chr1:56118465-56119167: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:57][Error] Unexpected error while processing region chr1:56119457-56120399: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:58][Error] Unexpected error while processing region chr1:56120663-56121527: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:58][Error] Unexpected error while processing region chr1:56122313-56123487: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:59][Error] Unexpected error while processing region chr1:102701849-102702550: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:59][Error] Unexpected error while processing region chr1:102702691-102704153: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:37:59][Error] Unexpected error while processing region chr1:102705542-102706243: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:112834134-112834835: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:151367004-151367705: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:151394270-151394971: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:153297161-153297862: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:153519816-153520524: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:154275992-154276693: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:155311624-155312325: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:155537646-155538350: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:160227716-160228417: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:162736713-162737429: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:172989449-172990150: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:194109288-194110318: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:203321379-203322163: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:205280742-205281443: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:205620842-205621543: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:212140806-212141507: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:221271669-221272370: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:226005810-226006511: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:228101042-228101743: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:231009903-231010604: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:246397575-246398276: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:247852345-247853046: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:35307121-35307851: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:00][Error] Unexpected error while processing region chr1:161004815-161005625: [Errno 2] No such file or directory: '/home/bioinfo1/anaconda3/envs/tricolorenv/lib/python3.8/site-packages/TRiCoLOR-1.1.0-py3.8.egg/TRiCoLOR/REFER/consensus'
> [17/04/2024 13:38:01][Message] Processing chromosome chr2
> [17/04/2024 13:38:01][Message] Creating .mmi index for current chromosome
> [17/04/2024 13:38:06][Message] Calling repetitions
